### ISSUE TITLE
Código de botón de compra

### ISSUE THREAD

**Issue by anacastello19** [CodeSystem2022/LosPitufos-CuartoSemestre#11]

**Comment by mayhrina30** [comment]
const buButton = document.createElement("button");
    buyButton.innerTEXT = "COMPRAR";

    content.append(buButton);

    buyButton.addEventListener("click", ()=>{
        cart.push({
            id: product.id,
            productName: product.productName,
            price: product.price,
            quanty: product.quanty,
            img: product.img,
        })
         console.log(cart)
    })



});
