### ISSUE TITLE
clase2(video1)  variables let y const , con ejecución en terminal

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/LosPitufos-CuartoSemestre#17]

**Comment by mairaggimenez** [comment]
console.log("Inicio de programa");
setTimeout(() =>    {
    console.log("Primer TIMEOUT");
}, 3000);

setTimeout(() =>    {
    console.log("Segundo TIMEOUT");
}, 0);

setTimeout(() =>    {
    console.log("Tercero TIMEOUT");
}, 0);

console.log("Fin de programa");
