### ISSUE TITLE
clase2(video2) Terminamos con un hola mundo y añadimos buena información sobre Node

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/LosPitufos-CuartoSemestre#18]

**Comment by anacastello19** [comment]
let nombre ='Ana';
console.log(nombre)
nombre='Juan';
console.log(nombre);

console.log('Hola mundo desde Node');

**Comment by EzequielgGarcia** [comment]
let nombre ='Eze';
console.log(nombre)
nombre='Pedro';
console.log(nombre);

console.log('Hola mundo desde Node');
