### ISSUE TITLE
clase3(video1) Función flecha con template String

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/LosPitufos-CuartoSemestre#19]

**Comment by jorolio** [comment]
const saludar = (nombre) =>{  //Funcion de flecha
    return `saludos de ${nombre}`; //usamos back tic`s
} // esto es igual a: 'saludos' + nombre;
console.log(saludar('Jorge'));

**Comment by jorolio** [comment]
console.log('inicio del programa');
setTimeout(() =>{
    console.log('Primer Timeout');
}, 3000);

setTimeout(() =>{
    console.log('Segundo Timeout');
}, 0);

setTimeout(() =>{
    console.log('Tercero Timeout');
}, 0);

console.log('Fin de programa')

**Comment by Luciano06663** [comment]
const saludar = (nombre) =>{ //Funcion de flecha
return saludos de ${nombre}; //usamos back tic`s
} // esto es igual a: 'saludos' + nombre;
console.log(saludar('Luciano));
