### ISSUE TITLE
Clase UsuarioDao

### ISSUE THREAD

**Issue by anacastello19** [CodeSystem2022/LosPitufos-CuartoSemestre#2]

**Comment by jorolio** [comment]
class UsuarioDAO:
    '''
    DAO -> Data Access Object Para la tabla de usuariuo
    CRUD -> Create - Read - Update - Delete
    '''

    _SELECT = 'SELECT * FROM usuario ORDER id ususario'
    _INSERTAR = 'INSERT INTO usuario (username, password) VALUE (%s, %s)'
    _ACTUALIZAR = 'UPDATE usuario SET username=%s, password=%s WHERE id_usuario'
    _ELIMINAR = 'DELETE FROM usuario WHERE id_usuario=%s'

    @classmethod
    def seleccionar(cls):
        with CursorDelPool() as cursor:
            log.debug('Seleccionando ususarios')
            cursor.execute(cls._SELECT)
            registros = cursor.fetchall()
            usuarios = []
            for registro in registros:
                usuario = Usuario(registro[0], registro[1], registro[2])
                usuarios.append(usuario)
            return usuarios

    @classmethod
    def insertar(cls, usuario):
        with CursorDelPool() as cursor:
            log.debug(f'Usuario a insertar: {usuario}')
            valores = (usuario.username, usuario.password)
            cursor.execute(cls._INSERTAR, valores)
            return cursor.rowcount

    @classmethod
    def actualizar(cls, usuario):
        with CursorDelPool() as cursor
            log.debug(f'Usuario a eliminar: {usuario}')
            valores = (usuario.id_usuario,)
            cursor.execute(cls._ELIMINAR, valores)
            return cursor.rowcount

**Comment by EzequielgGarcia** [comment]
from capa_datos_persona.cursor_del_pool import CursorDelPool
from logger_base import log

class UsuarioDAo:
    """
    Dao -> date access object para la tabla de usuario
    Crud -> Create - read - update - delete
    """
    _select = "select * from usuario orden by id_usuario"
    _insertar = "insert into usuario(username, password) value (%s, %s)"
    actualizar = "update usuarui set username=%s, password=%s where id_usuario=%s"
    eliminar = "delete from usuario where id_usuario=%s"

    @classmethod
    def seleccionar(cls):
        with CursorDelPool() as cursor:
            log.debug("seleccionar usuarios")
            cursor.execute(cls._select)
            registros = cursor.fetchall()
            usuarios = []
            for registro in registros:
                usuario = usuario(registro[0], registro[1], registro[2])
                usuarios.append(usuario)
            return usuarios
    @classmethod
    def insertar(cls, usuario):
        with CursorDelPool() as cursor:
            log.debug(f"usuario a insertar:{usuario}")
            valores = (usuario.username, usuario.password)
            cursor.execute(cls._insertar, valores)
            return cursor.rowcount
    @classmethod
    def actualizar(cls, usuario):
        with CursorDelPool() as cursor:
            log.debug(f"usuario a eliminar: {usuario}")
            valores= (usuario.id_usuario,)
            cursor.execute(cls._eliminar, valores)
            return cursor.rowcount
