### ISSUE TITLE
Método listarEstudiante

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/LosPitufos-CuartoSemestre#21]

**Comment by EzequielgGarcia** [comment]
import java.util.list;

public class estudiantesServicio implemets IEstudianteServicio{
    @Autowired
    private EstudiantesRepositorio estudiantesRepositorio;

    @Override
    public list<Estudiante> listarEstudiantes(){
        list<Estudiante> estudiantes = estudiantesRepositorio.FindAll();
        return estudiantes;
}
}
