### ISSUE TITLE
Creamos el objeto Logger

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/LosPitufos-CuartoSemestre#25]

**Comment by mairaggimenez** [comment]
package utn.tienda_libros.repositorio;

import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

public interface LibroRepositorio extends JpaRepository<Libro, Integer> {
    public List<Libro> listarLibro();
    public Libro buscarLibroPorId(Integer idLibro);
    public void guardarLibro(Libro libro);
    public void eliminarLibro(Libro libro);
}
