### ISSUE TITLE
dunder doc parte 1 y 2

### ISSUE THREAD

**Issue by jorolio** [CodeSystem2022/LosPitufos-CuartoSemestre#28]

**Comment by santimanas** [comment]
from mi_clase import MiClase

help(MiClase)

print(MiClase.__doc__)  #esto es solo para saber que MiClase esta aqui
print(MiClase.__init__.__doc__) #este metodo es el de inicio a clase
print(MiClase.mi_metodo.__doc__) #este metodo es un objeto y se le pueden dar parametros
print(type(MiClase.mi_metodo)) #esto muestra de que tipo es el metodo

**Comment by EzequielgGarcia** [comment]
from mi_clase import MiClase

help(MiClase)

print(MiClase.doc) #esto es solo para saber que MiClase esta aqui
print(MiClase.init.doc) #este metodo es el de inicio a clase
print(MiClase.mi_metodo.doc) #este metodo es un objeto y se le pueden dar parametros
print(type(MiClase.mi_metodo)) #esto muestra de que tipo es el metodo
