### ISSUE TITLE
Avanzamos desde una tupla

### ISSUE THREAD

**Issue by LucianaBaigorria** [CodeSystem2022/LosPitufos-CuartoSemestre#34]

**Comment by santimanas** [comment]
nombre = "Santiago"
edad = 20
mensaje_con_formato = 'Mi nombre es %s y tengo %d años' % (nombre, edad)

persona = ('Santiago','Mañas', 10000.00)
mensaje_con_formato = 'Hola %s %s. Tu sueldo es %.2f' % persona
print(mensaje_con_formato)
