### ISSUE TITLE
Uso del metodo format - parte 2

### ISSUE THREAD

**Issue by LucianaBaigorria** [CodeSystem2022/LosPitufos-CuartoSemestre#36]

**Comment by EzequielgGarcia** [comment]
nombre = "Juan"
edad = 19
Sueldo = 3000
 mensaje_con_formato = "nombre {} edad {} sueldo {:.2f}".format(nombre, edad, sueldo)
 Print(mensaje_con_formato)

mensaje = "sueldo {2:.2f} edad {1} nombre {0}". format(nombre, edad, sueldo)
Print(mensaje)
