### ISSUE TITLE
Parte 2 -> Probando y testeando

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/LosPitufos-CuartoSemestre#41]

**Comment by LucianaBaigorria** [comment]
import Router from "express-promise-router";
import {signin, signup,signout,profile } from"../controllers/auth.controllers.js";

const router = Router();

router.post("/signin",signin);

router.post("/signup", signup);

router.post("/signout", signout);

router.get("/profile", profile);

export default router;
