### ISSUE TITLE
7.4 Cookies -> Guardar el token en una cookie

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/LosPitufos-CuartoSemestre#44]

**Comment by jorolio** [comment]
const token = await createAccessToken({id: result.rows[0].id});
        console.log(result);
        res.cookie("token", token, {
            //httpOnly: true,
            secure : true,
            sameSite: "none",
            maxAge: 60 * 60 * 24 * 1000,}) // 1 day})
        return res.json(result.rows[0]);
