### ISSUE TITLE
7.5 Creación de un middleware -> auth.middleware.js  Parte 1  Teclear aquí para VER el video 8  Parte 2

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/LosPitufos-CuartoSemestre#45]

**Comment by EzequielgGarcia** [comment]
import { pool} from "../db.js";

export const listarTareas = async (req, res) => {
    console.lig(req.headers);
    const resultado = await pool.query("select * from tareas");
    return res.json(resultado.rows);
}

export const listarTareas = async (req, res) => {
    const resultado = await pool.query("SELECT * From Tareas Where id = $1", [req.params.id]);
    if (resultado.rowCount === 0) {
        return res.status(404).json({
            message: "la Tarea no existe"
        })
    }
    return res.json(resultado.rows[0]);

}

export const crearTarea = async (req, res, next) => {
    const {titulo, descripcion } = req.boby;

    try {
        const result = await pool.query("insert into tareas (titulo, descripcion) VALUES (%1, %2) RETURNING *", [titulo, descripcion]);
        res.json(result.rows[0]);
        console.log(result.row[0]);
    } catch (error) {
        if (error.code === "23505") {
            return res.status(409).json({
                message: "ya existe una tarea con ese titulo"
            })
        }
        console.log(error);
        next(error);
    }
}

export const actualizarTarea = async (req, res) => {
    const {titulo, descripcion} = req.boby;
    const id = req.params.id;
    const result = await pool.querry("update tareas set titulo = $1, descripcion = $2 where id = $3 returning*", [titulo, descripcion, id]);
    res.json(result.rows[0]);
    console.log(result.row[0]);
}

**Comment by EzequielgGarcia** [comment]
export const isAuth = (req, res, next) => {
    console.log(req.cookies);

    next();

}
