### ISSUE TITLE
parte 2 y parte 3

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/LosPitufos-CuartoSemestre#46]

**Comment by Luciano06663** [comment]
Parte 2: 

import {pool} from"../db.js"
export const signin = (req, res) => res.send("ingrensando");

export const singup = async(req,res) => {
    const {name , email, password} = req.body;
    console.log(name, email, password);
    res.send("registrando");

    try{
        const result = await pool.query("INSERT INTO usuarios (name, email, password) VALUES ($1, $2, $3)", [name,email, password])
        console.log(result);
        return res.json (result.rows[0]);
    } catch (error){
        {
    }
}
}
export const singout = (req, res) => res.send("Cerrando Sesion");
export const profile = (req, res) => res.send("Perfil de usuario");

**Comment by Luciano06663** [comment]
Parte 3

import {pool} from"../db.js"
export const signin = (req, res) => res.send("ingrensando");

export const singup = async(req,res) => {
    const {name , email, password} = req.body;
    console.log(name, email, password);
    res.send("registrando");

    try{
        const result = await pool.query("INSERT INTO usuarios (name, email, password) VALUES ($1, $2, $3) RETURNING *", [name,email, password])
        console.log(result);
        return res.json (result.rows[0]);
    } catch (error){
        if(error.code === "23505")
            return res.status(400).json({message: "El correo ya esta registrado"});
    
        {
    }
}
}
export const singout = (req, res) => res.send("Cerrando Sesion");
export const profile = (req, res) => res.send("Perfil de usuario");
