### ISSUE TITLE
Continuamos con constructor y metodo iniciarForma()

### ISSUE THREAD

**Issue by anacastello19** [CodeSystem2022/LosPitufos-CuartoSemestre#51]

**Comment by LucianaBaigorria** [comment]
package utn.tienda_libros;

import...
        
@SpringBootApplication
public class TiendaLibrosApplication {
    
    public static void main(String[] args) {SpringApplication.run(TiendaLibrosAplication..args.)}
       ConfigurableApplicationContext contextoSpring =
               new SpringApplicationBuilder(TiendaLibrosApplication.class)
