### ISSUE TITLE
Parte 2 Botones para modificar, eliminar y damos forma visual

### ISSUE THREAD

**Issue by santimanas** [CodeSystem2022/LosPitufos-CuartoSemestre#56]

**Comment by jorolio** [comment]
package utn.tienda_libros.vista;

import org.springframework.beans.factory.annotation.Autowired;
import utn.tienda_libros.servicio.LibroServicio;

import javax.swing.*;

public class LibroFrom extends JFrame {
    LibroServicio libroServicio;
    private JPanel panel;

    @Autowired
    public LibroFrom(LibroServicio libroServicio){
        this.libroServicio = libroServicio;
        iniciarFrom();
    }

    private void iniciarFrom(){
        setContentPane(panel);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        setSize(900, 700);
    }
}
