### ISSUE TITLE
Acción del botón Agregar -> Agregar libro con Swing  Parte 2

### ISSUE THREAD

**Issue by santimanas** [CodeSystem2022/LosPitufos-CuartoSemestre#58]

**Comment by anacastello19** [comment]
private void agregarLibro(){
        //Leer lod valores del formulario
        if(libroTexto.getText().equals("")){
            mostrarMensaje("Ingresa el nombre del libro");
            libroTexto.requestFocusInWindow();
            return;
        }
        var nombreLibro= libroTexto.getText();
        var autor= autorTexto.getText();
        var precio= Double.parseDouble(precioTexto.getText());
        var existencias= Integer.parseInt(existenciasTexto.getText());
        //Creamos el objeto libro
        var libro= new Libro();
        libro.setNombreLibro(nombreLibro);
        libro.setAutor(autor);
        libro.setPrecio(precio);
        libro.setExistencias(existencias);
    }
