### ISSUE TITLE
pruebas de la Clase UsuarioDAO y menu_app_usuario

### ISSUE THREAD

**Issue by anacastello19** [CodeSystem2022/LosPitufos-CuartoSemestre#6]

**Comment by mairaggimenez** [comment]
opcion = None
while opcion != 5:
    print("opciones: ")
    print("1. Listar Usuarios")
    print("2.Agregar Usuario")
    print("3.Modificar Usuario")
    print("4.Eliminar Usuario")
    print("5.Salir")
    opcion = int(input("Digite la opcion entre 1-5"))
    if opcion ==1:
        usuarios = UsuarioDAO.seleccionar()
        for usuario in usuarios:
            log.info(usuario)
    elif opcion == 2:
        username_var = input("Digite el nombre del usuario: ")
        password_var = input("Digite su contaseña: ")
        usuario = Usuario(username=username_var, password=password_var)
        usuario_insertado = UsuarioDAO.insertar(usuario)
        log.info(f"Usuario insertado: {usuario_insertado}")
    elif opcion == 3:
        id_usuario_var = int(input("Digite id usuario a modificar: "))
        username_var = input("Digite ek nombre del usuarui a modificar: ")
        password_var = input("Digite la contraseña usuario a moficar: ")
        usuario = Usuario(id_usuario=id_usuario_var,username=username_var,password=password_var)
        usuario_actualizado = UsuarioDAO.actualizar(usuario)
        log.info(f"Usuario actualizado:{usuario_actualizado}")
    elif opcion ==4:
        id_usuario_var = int(input("Digite id usuario a eliminar: "))
        usuario = Usuario(id_usuario=id_usuario_var)
        usuario_eliminado = UsuarioDAO.eliminar(usuario)
        log.info(f"Usuario eliminado:{usuario_eliminado}")
else:
    log.info("Salimos de la aplicacion, hasta pronto")

**Comment by Luciano06663** [comment]
if __name__ == '__main__'
        # Eliminar usuario
    usuario = usuario(id_usuario=3)
    usuario_eliminado = UsuarioDAO.eliminar(usuario)
    log.debug(f'Usuario eliminado: {usuario_eliminado}')

    #Actualizar usuario
    usuario = Usuario(id_usuario=1, username= '', password='369')
    usuario_modificiado = UsuarioDAO.actualizar(usuario)
    log.debug(f'Usuario modificiado: {usuario_modificiado}')

    #Insertar usuario
    usuario = Usuario(username= 'Kely', password='321')
    usuario_insertado = UsuarioDAO.insertar(usuario)
    log.debug(f'Usuario insertado: {usuario_insertado}')

     # Listar o seleccionar
        usuarios = UsuarioDAO.seleccionar()
        for usuario in usuarios
            log.debug(usuario)
