### ISSUE TITLE
Comienzo de proyecto

### ISSUE THREAD

**Issue by anacastello19** [CodeSystem2022/LosPitufos-CuartoSemestre#7]

**Comment by Luciano06663** [comment]
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale">
        <link rel="stylesheet" href="styles.css">
        <title>Document</title>

    </head>
    <body>
        
        <div class = "card-products-container">
            <div class="card-products" id="ShopContent"></div>
        </div>

        <script src="/client/js/products.js"></script>
        <script src="/client/js/index.js"></script>
    </body>
</html>
