### ISSUE TITLE
applicacion.yml con variables de entorno

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/LosPitufos-CuartoSemestre#72]

**Comment by LucianaBaigorria** [comment]
spring:
  application:
    name: todo-app
  datasource:
    driver-class-name: Comment.mysql.cj.jdbc.driver
    username: ${DB_USER}
    password:${DB_PASS}
    url:"jdbc:mysql://localhost:3306/db_todo_api?createDatabaseIfNotExist=true"
  jpa:
    show-sql:true
    database: mysql
    database-platform: origin.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    properties:
       hibernate:
         format_sql: true
    hibernate:
       ddl-auto: update 
output:
  ansi:
    enabled: always

**Comment by anacastello19** [comment]
spring:
application:
name: todo-app
datasource:
driver-class-name: Comment.mysql.cj.jdbc.driver
username: ${DB_USER}
password:${DB_PASS}
url:"jdbc:mysql://localhost:3306/db_todo_api?createDatabaseIfNotExist=true"
jpa:
show-sql:true
database: mysql
database-platform: origin.hibernate.dialect.MySQL8Dialect
defer-datasource-initialization: true
properties:
hibernate:
format_sql: true
hibernate:
ddl-auto: update
output:
ansi:
enabled: always
