### ISSUE TITLE
Carga del codigo HTLM y CSS

### ISSUE THREAD

**Issue by anacastello19** [CodeSystem2022/LosPitufos-CuartoSemestre#8]

**Comment by jorolio** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css">
    <title>Document</title>
</head>
<body>
    
    <div class="card-products-container">
        <div class="card-products" id="shopContent"></div>
    </div>
    
    <div class="cart-btn" id="cart-btn">🛒</div>

    
    <div class="modal-overlay" id="modal-overlay"></div>
    <div class="modal-container" id="modal-container"></div>

    <script src="/client/js/product.js"></script>
    <script src="/client/js/index.js"></script>
    <script src="js/cart.js"></script>
    
</body>
</html>

**Comment by jorolio** [comment]
/*products styles*/
.card-products-container {
    margin: 5vh auto;
}

.card-products {
    text-align: center;
    display: flex;
    flex-direction: row;
    justify-content: space-around;
    flex-wrap: wrap;
}

.card-products img {
    margin-top: 40px;
    width: 250px;
    height: 250px;

}

.card-products button {
    border: none;
    outline: 0;
    padding: 10px;
    color: white;
    background-color: aquamarine;
    text-align: center;
    cursor: pointer;
    width: 100%;
    font-size: 15px;

}

.card-products button:hover {
    opacity: 0.7;
}

.cart-btn {
    position: fixed;
    top: 90vh;
    right: 40px;
    background-color: rgb(25, 25, 25);
    padding: 10px;
    border-radius: 50%;
    height: 24px;
    width: 24px;
    transition: transform 0.2s ease-in-out;
}

.cart-btn:hover {
    cursor: pointer;
    opacity: 0.9;
}

**Comment by jorolio** [comment]
const productos = [
    {
        id: 1,
        productName: "TOMATE",
        price: 500,
        quanty: 1,
        img: "C:/client/media/TOMATE.jpg",
    },
    {
        id: 2,
        productName: "BANANA",
        price: 800,
        quanty: 1,
        img: "/client/media/BANANA.jpg",

    },
    {
        id: 3,
        productName: "MANDARINA",
        price: 600,
        quanty: 1,
        img: "/client/media/MANDARINA.jpg",
    }
]
