### ISSUE TITLE
Creamos los archivos de main.py y charts.py

### ISSUE THREAD

**Issue by Luciano06663** [CodeSystem2022/LosPitufos-CuartoSemestre#81]

**Comment by EzequielgGarcia** [comment]
main.py
 (va en blanco )

charts.py


import matplotlib.pyplot as plt

def generate_pie_chart():
      labels = ['A', 'B', 'C']
      values = [200, 34, 120]

      fig, ax = plt.subplots()
      ax.pie(values, labels=labels)
      plt.savefig('pie.png')

      plt.close()
