### ISSUE TITLE
Avances de HTML y CSS

### ISSUE THREAD

**Issue by anacastello19** [CodeSystem2022/LosPitufos-CuartoSemestre#9]

**Comment by LucianaBaigorria** [comment]
const shopContent = document.getElementById("shopContent");

productos.forEach(product) => {
    const content = document.createElement("div");
    content.innerHTML = `
    <img src="${product.img}">
    <h3>${product.productName}</h3>
    <p>${product.price} $</p>
    `;
    shopContent.append(content);
    
    
});
